#!/bin/bash

set -o errexit
set -o xtrace

cd "$(dirname "$(realpath "$0")")"

if [ ! -e /dev/fb1 ]; then
    # screen isn't present, try flashing the Xilinx
    sudo gz_load /home/pi/Guzunty/Pi/src/gz_lcd/gz_lcd.xsvf
else
    # screen is present, run the test program
    sudo tbtool tingbot_run test_routine.tingapp
fi

sudo shutdown -r now
