#!/bin/bash

set -o errexit
set -o xtrace

cd "$(dirname "$(realpath "$0")")"

TEST_FLAG=/home/pi/TEST_MODE

if [ ! -f $TEST_FLAG ]; then
    # first boot, try flashing the Xilinx
    sudo gz_load /home/pi/Guzunty/Pi/src/gz_lcd/gz_lcd.xsvf
    # make the test flag so we restart in test mode
    touch $TEST_FLAG
else
    # second boot, run the test program
    rm $TEST_FLAG
    sudo tbtool tingbot_run test_routine.tingapp
fi

sudo shutdown -r now
